[build]
builder = "python"
python.version = "3.11"
install = ["python-telegram-bot==21.9", "python-dotenv", "flask", "requests"]

[deploy]
startCommand = "python raidar_bot.py"
runtime = "python"
env = ["BOT_TOKEN", "TWITTER_CLIENT_ID", "TWITTER_CLIENT_SECRET", "CALLBACK_URL", "FLASK_SECRET"]
